---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  namespace: monitoring
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  nfs:
    path: /mnt/nfsshare
    server: 192.168.0.160


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 25Gi


---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  selector:
    env: metrics
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30001


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config-cfgmap
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     30s
      evaluation_interval: 30s
      
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]

      - job_name: 'plants'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
            - 192.168.0.132:9090
            - 192.168.0.133:9090

      - job_name: 'greenhouse'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
            - 192.168.0.135:9090

      - job_name: 'outside'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
            - 192.168.0.130:9090
      
      - job_name: 'home'
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
            - 192.168.0.131:9090
            
      - job_name: "node_exporter"
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets: ["node-exporter:9100"]
            #            - 10.42.0.51:9100
            #            - 10.42.1.37:9100
            #            - 10.42.2.72:9100
            


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    env: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      env: metrics
  template:
    metadata:
      name: prometheus
      labels:
        env: metrics
    spec:
      containers:
      - image: prom/prometheus
        name: prom
        args:
        - --config.file=/mnt/nfsshare/prometheus/prometheus.yml
        - --storage.tsdb.path=/mnt/nfsshare/prometheus_data/
        - --log.level=debug
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: prometheus-volume
          mountPath: /mnt/nfsshare/prometheus
          subPath: prometheus
        - name: prometheus-volume
          mountPath: /mnt/nfsshare/prometheus_data
          subPath: prometheus_data 
        - name: prometheus-script
          mountPath: /mnt/nfsshare/prometheus/prometheus.yml
          subPath: prometheus.yml  
      volumes:
      - name: prometheus-script
        configMap:
          name: prometheus-config-cfgmap
      - name: prometheus-volume
        persistentVolumeClaim:
          claimName: prometheus-nfs-pvc

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: monitoring
rules:
- apiGroups: [""]
  resources:
  - persistenvolumes
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring
